int    CSPloadprob1(int,int*,double*,int*,char*,
                   double*,double*,double*,double*);
int    CSPloadprob2(int,int,int*,int*,double*,int*,char*,
                   double*,double*,double*,double*);
int    CSPloadprob3(int,int,int,int*,int*,int*,double*,int*,char*,
                   double*,double*,double*,double*);
int    CSPloadprob4(int,int,int,int,int*,int*,int*,int*,double*,int*,char*,
                   double*,double*,double*,double*);
